import type { Chapter, PersonalizationEntry } from '@/types'

export const CHAPTERS: Chapter[] = [
  { id:'ch001', num:'Chapter 001', cat:'nature',   icon:'nature',    ltr:'H',
    title:'A wild trout, before Tokyo wakes.',
    line:'Private fly fishing on mountain rivers, western Tokyo.',
    host:'Hiroyuki Oka · Founder & Host', loc:'Akigawa Valley',
    season:'Mar – Oct', badge:'One party per day', status:'act', stTxt:'Nature · Active', detail:true },
  { id:'ch002', num:'Chapter 002', cat:'culinary',  icon:'culinary',  ltr:'S',
    title:'One table. One chef. One afternoon.',
    line:'Fermentation, miso, and a meal you helped make.',
    host:'Chef Saito Ryo', loc:'Koenji, Tokyo',
    season:'Year-round', badge:'One sitting per day', status:'rev', stTxt:'Culinary · In review' },
  { id:'ch003', num:'Chapter 003', cat:'creative',  icon:'creative',  ltr:'K',
    title:'Leave with something you made.',
    line:'A full day with a documentary filmmaker.',
    host:'Mori Keiko', loc:'Shimokitazawa',
    season:'Year-round', badge:'One guest per day', status:'rev', stTxt:'Creative · In review' },
  { id:'ch004', num:'Chapter 004', cat:'connect',   icon:'connect',   ltr:'A',
    title:'A letter. A conversation. A long-overdue day.',
    line:'Guided reconnection with someone you lost touch with.',
    host:'ECV Concierge', loc:'Tokyo',
    season:'Year-round', badge:'Private · By arrangement', status:'rev', stTxt:'Reconnect · In curation' },
  { id:'ch005', num:'Chapter 005', cat:'family',    icon:'family',    ltr:'F',
    title:'A day worth two generations.',
    line:'A private experience designed for parent and child.',
    host:'ECV · Family chapter', loc:'Western Tokyo',
    season:'Mar – Oct', badge:'Families welcome', status:'rev', stTxt:'Family · In curation' },
  { id:'ch006', num:'Chapter 006', cat:'nature',    icon:'stillness', ltr:'T',
    title:'The city disappears.',
    line:'A half-day in cedar forest. No guide. No agenda.',
    host:'ECV · Solo chapter', loc:'Okutama',
    season:'Apr – Nov', badge:'Solo only', status:'rev', stTxt:'Stillness · In curation' },
  { id:'ch007', num:'Chapter 007', cat:'connect',   icon:'gratitude', ltr:'G',
    title:'Return what you were given.',
    line:'Arigato Once More — for someone who changed something in you.',
    host:'ECV · Gratitude chapter', loc:'Tokyo & beyond',
    season:'Year-round', badge:'One gift at a time', status:'rev', stTxt:'Gratitude · In curation' },
  { id:'ch008', num:'Chapter 008', cat:'creative',  icon:'learning',  ltr:'Y',
    title:'One day. One discipline. One teacher.',
    line:'Marine biology field day on Sagami Bay.',
    host:'Yamamoto Hiroshi', loc:'Kanagawa',
    season:'May – Sep', badge:'One party per day', status:'rev', stTxt:'Learning · In review' },
  { id:'ch009', num:'Chapter 009', cat:'culinary',  icon:'urban',     ltr:'H',
    title:'Tokyo, seen from the inside.',
    line:'A day with someone who knows a neighbourhood differently.',
    host:'ECV · Urban chapter', loc:'Various, Tokyo',
    season:'Year-round', badge:'Two guests max', status:'rev', stTxt:'Urban · In curation' },
  { id:'ch010', num:'Chapter 010', cat:'family',    icon:'legacy',    ltr:'L',
    title:'Pass something on.',
    line:'A day designed to create a memory across generations.',
    host:'ECV · Legacy chapter', loc:'Tokyo & surrounds',
    season:'Year-round', badge:'Family only', status:'rev', stTxt:'Legacy · In curation' },
]

export const PERSONALIZATION: Record<string, PersonalizationEntry> = {
  'Being in nature': {
    greet:'The river is always quiet.',
    why:'Showing experiences shaped around nature, solitude, and the natural world.',
    pb:{ eye:'ECV Registry — Nature & Stillness',
         t:'"Where the city ends and the real world begins."',
         act:'Chapter 001, 006 available · more in curation →' },
    fc:'ch001', homeIds:['ch006','ch005','ch002','ch004','ch007','ch003','ch008','ch009','ch010'],
  },
  'Making something': {
    greet:"Find the maker's hour.",
    why:'Showing experiences shaped around craft, creativity, and making things with your hands.',
    pb:{ eye:'ECV Registry — Creative & Learning',
         t:'"Some experiences leave something behind."',
         act:'Chapter 003, 008 in review · more in curation →' },
    fc:'ch003', homeIds:['ch008','ch002','ch001','ch006','ch005','ch004','ch007','ch009','ch010'],
  },
  'Sharing a meal': {
    greet:'A table worth remembering.',
    why:'Showing experiences shaped around food, conversation, and the ritual of eating together.',
    pb:{ eye:'ECV Registry — Culinary & Gathering',
         t:'"One table. One afternoon. That\'s enough."',
         act:'Chapter 002, 009 in review →' },
    fc:'ch002', homeIds:['ch009','ch004','ch001','ch007','ch005','ch003','ch006','ch008','ch010'],
  },
  'Learning slowly': {
    greet:'Knowledge you can touch.',
    why:'Showing experiences shaped around deep attention, craft, and learning by doing.',
    pb:{ eye:'ECV Registry — Learning & Discovery',
         t:'"Some knowledge only comes through being present."',
         act:'Chapter 008, 003 in review →' },
    fc:'ch008', homeIds:['ch003','ch001','ch006','ch002','ch005','ch004','ch007','ch009','ch010'],
  },
  'Moving through a place': {
    greet:'Discover Tokyo differently.',
    why:'Showing experiences shaped around local knowledge and seeing places from the inside.',
    pb:{ eye:'ECV Registry — Urban & Cultural',
         t:'"Every city has a version most visitors never find."',
         act:'Chapter 009, 001 available →' },
    fc:'ch001', homeIds:['ch009','ch006','ch002','ch003','ch005','ch004','ch007','ch008','ch010'],
  },
  'Time with family': {
    greet:"A day they won't forget.",
    why:'Showing experiences shaped for shared memory across generations.',
    pb:{ eye:'ECV Registry — Family & Legacy',
         t:'"Some experiences are better with the people who matter most."',
         act:'Chapter 005, 010 in curation →' },
    fc:'ch005', homeIds:['ch010','ch001','ch007','ch004','ch002','ch003','ch006','ch008','ch009'],
  },
  'Quiet & stillness': {
    greet:'Silence, carefully arranged.',
    why:'Showing experiences shaped around slowness, quiet, and being away from noise.',
    pb:{ eye:'ECV Registry — Stillness & Solitude',
         t:'"Not everything worth finding is loud."',
         act:'Chapter 006, 001 available →' },
    fc:'ch006', homeIds:['ch001','ch004','ch007','ch005','ch010','ch002','ch003','ch008','ch009'],
  },
  "Something I can't name": {
    greet:"Let's find it together.",
    why:'Showing the full registry — sometimes the right experience is the one you couldn\'t describe.',
    pb:{ eye:'ECV Registry — All Chapters',
         t:'"Start anywhere. Something will feel right."',
         act:'Browse all ten chapters →' },
    fc:'ch001', homeIds:['ch002','ch003','ch005','ch006','ch007','ch008','ch009','ch010','ch004'],
  },
}

export const DEFAULT_PERSONALIZATION = PERSONALIZATION["Something I can't name"]
